### ISSUE TITLE
Tables don't carry between nuts

### ISSUE THREAD

**Issue by KelvinShadewing** [albertodemichelis/squirrel#102]
I've found that just about every data type other than a table will carry between nuts when multiple nuts are run during the same execution. For example, I made these three tests:

**TEST 1**

*File 1*
```
const foo = "TEST";
```

*File 2*
```
print(foo);
```

Output : `TEST`

**TEST 2**

*File 1*
```
class Foo{
  constructor(){
    print("TEST");
  };
};
```

*File 2*
```
Foo();
```

Output : `TEST`

**TEST 3**

*File 1*
```
local foo = {};
```

*File 2*
```
foo.bar <- "TEST";
print(foo.bar);
```

Output : `AN ERROR HAS OCCURED [the index 'foo' does not exist]`

For some reason, when I make `foo` a table, it doesn't exist when the second file is run. Any ideas?

**Comment by zeromus** [comment]
You didnt "make `foo` a table", you "made `foo` a local table". The definition of local is: it shall not carry exist between runs (scopes)

**Comment by KelvinShadewing** [comment]
Oh, so a different nut file counts as its own scope? I thought that the VM just ran the code from a nut and then waited for the next one. How do I make it carry over?

**Comment by zeromus** [comment]
use `foo <- {}`

`class foo {}` is shorthand for `foo <- class {}` ; now you should see why that works.

`const` is special: it does automatically carry over. it enters a value in a global persistent constant table

**Comment by KelvinShadewing** [comment]
I see. I also tried doing `::foo <- {};` and that seemed to work, too. Thank you!
