### ISSUE TITLE
print(array)

### ISSUE THREAD

**Issue by comarius** [albertodemichelis/squirrel#106]
Presuming nut code:
```javascript
    local g = reveiveBytes() // returns array[]
    print(g);   - > prints array:0x#####.
```
I did a hack to sqbaselib as:
so something like: 
```javascript
    local l = [4,5,6,7,"ffff", false, 3.4];
    print(l);
```
would print 
```javascript
    array[7]=[4, 5, 6, 7, "ffff", ?, ?, ]

```

```javascript
static SQInteger base_print(HSQUIRRELVM v)
{
    const SQChar *str;
    SQObjectPtr &o = stack_get(v, 2);

    //mco-mco { added print for array
    if(sq_isarray(o) || sq_istable(o))
    {
        sq_pushobject(v,o);
        int ret = sq_getsize(v,-1);
        sq_pop(v,1);
        if(_ss(v)->_printfunc)
            _ss(v)->_printfunc(v,_SC("array[%d]=["),ret);

        for(int i = 0; i<ret; ++i)
        {
            HSQOBJECT slotObj;
            sq_pushobject(v, o);
            sq_pushinteger(v, i);
            if(!SQ_FAILED(sq_get(v, -2)))
            {
                sq_getstackobj(v, -1, &slotObj);
                sq_pop(v, 2);
                if(sq_isinteger(slotObj))
                {
                    if(_ss(v)->_printfunc)
                        _ss(v)->_printfunc(v,_SC("%d, "),slotObj._unVal.nInteger);
                }
                else if(sq_isstring(slotObj))
                {
                    if(_ss(v)->_printfunc)
                    {
                        _ss(v)->_printfunc(v,_SC("\"%s\", "),slotObj._unVal.pString->_val);
                    }
                }
                else{
                    if(_ss(v)->_printfunc)
                    {
                        _ss(v)->_printfunc(v,_SC("?, "),slotObj._unVal.pString->_val);
                    }
                }
            }
            else
                sq_pop(v, 1);
        }
        if(_ss(v)->_printfunc)
            _ss(v)->_printfunc(v,_SC("]\n"),ret);

        return 0;
    }
    else
    {
        if(SQ_SUCCEEDED(sq_tostring(v,2)))
        {
            if(SQ_SUCCEEDED(sq_getstring(v,-1,&str))) {
                if(_ss(v)->_printfunc) _ss(v)->_printfunc(v,_SC("%s"),str);
                return 0;
            }
        }
    }
    return SQ_ERROR;
}
```

**Comment by zeromus** [comment]
Is there a bug here or are you just sharing your function? squirrel can't work the way you made it work, that would need to be part of a serialization facility. 

I think squirrel could probably use a lean C json api set though. Does anybody have one? I made one I haven't tested much which uses the squirrel stack (no recursion) and scratchpad. Since I had allocated memory for squirrel already, I wanted it to use that memory. IMO that's the squirreliest way to do it, but I can see why someone else might think it should appear to be some kind of magic resource-less allocation from the point of view of a squirrel user (and not use its stack).

**Comment by comarius** [comment]
Just sharing.
Thank you.

**Comment by mingodad** [comment]
Hello !
When writing strings you should also escape then if they include embedded '"' and probably others.
Cheers !

**Comment by comarius** [comment]
Hello,
though I have a question.

I am calling a function from C++ to script passing an array of bytes.

size_t len =1;
Sqrat::Array ra(Penv->theVM(), len);

 for(size_t idx = 0 ; idx < len; idx++)
 {
       ra.Insert(idx, uint8_t(data[idx]));
 }
 Sqrat::SharedPtr<int> rv = _procFunc.Evaluate<int>(this, ra);

but in script I get 2 as the length of the array

function PROC(dev, data)
{
    print("\n");
    print(dev);
    print(data);
    print("array length="); print(data.len());
    return 0;
}


(instance : 0x0x1a1c170)(array : 0x0x7f2ff80008c0)array length=2

Anything you spot I am doing wrong ?


Thank you.

**Comment by zeromus** [comment]
You have an array of length 1. You Insert() one element. You now have an array of length 2.

**Comment by comarius** [comment]
Thank you.
