### ISSUE TITLE
Fix to allow throw NULL exceptions

### ISSUE THREAD

**Issue by mingodad** [albertodemichelis/squirrel#107]
Hello !
I recently needed to implement a class _get meta method using the C api and found that we can not throw NULL exceptions to achieve what's documented on the docs:
```
_get
invoked when the index idx is not present in the object or in its delegate chain. 
_get must 'throw null' to notify that a key wasn't found but the there were not runtime 
errors(clean failure). This allows the program to defferentieate between a runtime error 
and a 'index not found'.

function _get(idx) //return the fetched values
``` 

Here is the fix for SquiLu https://github.com/mingodad/squilu/commit/06002f3ad5df8985084ea1f7600e6b99c069a9b3
Cheers !

**Comment by albertodemichelis** [comment]
you can throw null in squirrel already, you must use sq_throwobject().
