### ISSUE TITLE
Unexpected closure error

### ISSUE THREAD

**Issue by mingodad** [albertodemichelis/squirrel#108]
Hello !
I'm converting tests from lua 5.1 ( http://www.inf.puc-rio.br/~roberto/lua/lua5.1-tests.tar.gz ) to SquiLu/Squirrel and found several unexpected errors.
Like this one for closures:
```
print( "testing closures and coroutines\n" )

// testing closures with 'for' control variable
local a = []
for(local i=0; i < 10; ++i)
{
  a.append({set = function(x){ i=x; }, get = function (){ return i; }})
  if( i == 2 ) break;
}
assert(a.len() == 3)
//code to debug start
a[0].set(10)
print("get")
print(a[0].get)
print("\n")
print("get")
print(a[0].get())
print("\n")
print("get")
print(a[1].get())
print("\n")
print("get")
print(a[1].get)
print("\n")
print("get")
print(a[2].get())
print("\n")
print("get")
print(a[2].get)
print("\n")
//code to debug end
assert(a[1].get() == 1)
a[1].set('a')
assert(a[2].get() == 2)
assert(a[1].get() == 'a')

```
Result:
```
testing closures and coroutines
get(function : 0x0x9cfd50)
get(function : 0x0x9c5e50)
get(function : 0x0x9c5e50)
get(function : 0x0x9d0c30)
get(function : 0x0x9c5e50)
get(function : 0x0x9ce060)

AN ERROR HAS OCCURRED [assertion failed]

CALLSTACK
*FUNCTION [main()] closure.nut line [32]

LOCALS
[a] ARRAY
[vargv] ARRAY
[this] TABLE
```

Here is the original lua 5.1 code (that works):
```
-- testing closures with 'for' control variable
a = {}
for i=1,10 do
  a[i] = {set = function(x) i=x end, get = function () return i end}
  if i == 3 then break end
end
assert(a[4] == nil)
a[1].set(10)
assert(a[2].get() == 2)
a[2].set('a')
assert(a[3].get() == 3)
assert(a[2].get() == 'a')
```

Here is another simple variation that also fails:
```
// testing closures with 'for' control variable x break

local f

for(local i=1; i <= 3; ++i)
{
  f = function () { return i;}
  break
}
assert(f() == 1)
```
Output:
```
AN ERROR HAS OCCURRED [assertion failed]

CALLSTACK
*FUNCTION [main()] closure.nut line [10]

LOCALS
[f] CLOSURE
[vargv] ARRAY
[this] TABLE
```

**Comment by zeromus** [comment]
seems like you can work around this with `local j = i;` and that's a pretty good clue about what's needed to fix this. squirrel should probably be doing this implicitly in each iteration for every local variable declared in the 1st part of the `for` construct.

here's a simpler test
```
local c;
for(local i=0; i < 1; ++i)
	if(i==0) c = function (){ return i; }

print(c()); //should print 0 but prints 1
```

**Comment by mingodad** [comment]
Good catch !

**Comment by mingodad** [comment]
Looking through the code I can see that Squirrel/SquiLu capture the for loop "i" variable as an outervalue by reference so when we execute we get the current value of it, so I'm not sure if it could ever behave like Lua.

```
local c, i;
for(i=0; i < 1; ++i)
{
	if(i==0) c = function (){ return i; }
}

print(c()); //should print 0 but prints 1

i = 45;
print(c()); //should print 0 but prints 45


for(i=0; i < 1; ++i)
{
	local j=i;
	if(i==0) c = function (){ return j; }
}

print(c()); //print 0
```

**Comment by zeromus** [comment]
actually with squirrel scoping, can we make this transformation (I didnt check)

`for(local X;...) statement;`
->
`for(local X;...) { local __poop = X; { local X = __poop; statement; } }`

**Comment by mingodad** [comment]
Thanks to your feedback I found this and it seems that it can be a font of some obscure bugs:
```
for(local j=0; j < 1; ++j)
{
	if(j==0) c = function (){j+= 3; return j; }
}

print(c()); //print 4
print(c()); //print 7
```

**Comment by zeromus** [comment]
I don't think that's a bug. I would expect that to be the case in squirrel. The closure captures a writeable variable. The only bug I've seen here is that the writeable variable needs to be virtualized within a for loop iteration instead of.. broken.

**Comment by mingodad** [comment]
Looking at it again I agree with you, so we should not expect Lua parity behavior here:
```
local c, d
for(local j=0; j < 10; ++j)
{
	if(j==0) c = function (){j+= 3; return j; }
	if(j==1) d = function (){j+= 5; return j; }
}

print(c()); //print 13
print(c()); //print 16
print(d()); //print 21
print(c()); //print 24
print(d()); //print 29
```

**Comment by zeromus** [comment]
Are these the results from lua? I do not mind these results. This makes it look like lua creates one variable for the entire loop, and both `c` and `d` get it--and the loop gets it too. I'm OK with that, and I might actually vote for squirrel to work that way. It's simpler than the other way I've proposed. Actually I think maybe that's how it was meant to work in squirrel, it's just broken (the variable turns to nonsense after the end of the loop). That means I disagree with my own "should print 0 but prints 1"

Let's put it this way: it's this transformation instead of the other one I listed:

`for(local X;...) statement;`
->
`{ local X; for(;...) statement; }`

That's pretty simple. why not? That's almost exactly what the compiler looks like!

**Comment by mingodad** [comment]
The previous sample are from Squirrel/SquiLu.

**Comment by zeromus** [comment]
Oh. well. If what squirrel did happened to match lua, that would be nice. But I would judge whether squirrel was doing best independently; and I think that example looked fine.

**Comment by mingodad** [comment]
Thanks to you again I found a bug in SquiLu not present in Squirrel, trying to write tests for Squirrel/SquiLu can be an important step to ensure correctness.

The code bellow converted from Lua works fine in Squirrel but fails with SquiLu so I'll try to find what I did to mess here:
```
// testing closures with 'for' control variable
local a = []
for(local i=0; i < 10; ++i)
{
  local lv = i;
  a.append({set = function(x){ lv=x; }, get = function (){ return lv; }})
  if( i == 2 ) break;
}
assert(a.len() == 3)
assert(a[0].get() == 0)
a[0].set(10)
assert(a[0].get() == 10)
assert(a[1].get() == 1)
a[1].set('a')
assert(a[1].get() == 'a')
//a[2].set(2)
assert(a[2].get() == 2)  //SquiLu fails here
```

**Comment by albertodemichelis** [comment]
I pushed a fix for this.

**Comment by mingodad** [comment]
I'm not sure what your fix is for because the example here https://github.com/albertodemichelis/squirrel/issues/108#issuecomment-341537580 do not works if we do not use locals.

**Comment by albertodemichelis** [comment]
For Squirrel the "i" is outside the for loop scope so it behaves differently than Lua. I'm actually surprised that Lua "closes" the control variable each iteration.
