### ISSUE TITLE
Block scope ?

### ISSUE THREAD

**Issue by mingodad** [albertodemichelis/squirrel#11]
Hello !
With the latest pull request it becomes easier to if accepted add block scopes as it's already implemented in squilu.
It's like C/C++ scope rules anytime we open "{" and close "}" (except for tables) this way also like in C++ objects declared inside scopes are garbage collected at the end of the scope.
With scopes and the compiler ability to emit warnings we can check for already defined constants/variables and emit an error/warning if they shadow already declared variables in outer scopes.
All of this is already implemented in squilu basically since it's beginning.

Can I make a pull request with it ?
Cheers !

**Comment by zeromus** [comment]
Sounds a little interesting to me, and maybe something I could use one day, but probably kind of a bulky change for an obscure purpose. To be honest, I would wait for someone other than a guy trying to compile C++ code in squirrel to ask for it!

**Comment by albertodemichelis** [comment]
nop
