### ISSUE TITLE
It seems that pcall doesn't work as documented

### ISSUE THREAD

**Issue by mingodad** [albertodemichelis/squirrel#110]
Hello !
Continuing converting tests from Lua to Squirrel/SquiLu I found that the pcall doesn't work as documented:
```
pcall(_this,args...)
calls the function with the specified environment object(’this’) and parameters,
this function will not invoke the error callback in case of failure(pcall stays for 'protected call')
```

Squirrel/SquiLu code:
```
function wrong(a){return b;}
print(wrong.pcall(this, 3));
```
Output:
```
AN ERROR HAS OCCURED [the index 'b' does not exist]

CALLSTACK
test-pm.nut:2:0 *FUNCTION [main()]

LOCALS
[vargv] ARRAY
[this] TABLE
```

Lua code:
```
function wrong(a) return b end
print(pcall(wrong, 3));
```
Output:
```
true	nil
```
Here is the actual code:
```
static SQRESULT closure_pcall(HSQUIRRELVM v)
{
	return SQ_SUCCEEDED(sq_call(v,sq_gettop(v)-1,SQTrue,SQFalse))?1:SQ_ERROR;
}
```
It's calling the function with raiseerror=SQFalse but it's returning SQ_ERROR if it fail and hence causing the program to halt.
Lua with multiple return solve this returning the error code and the function return result.
Squirrel/SquiLu only return one result and is raising an error if it doesn't succeed.

Returning an array with the two results is one solution but it changes the behavior, someone have a good alternative ?

Cheers !

**Comment by mingodad** [comment]
My experience so far is that Squirrel/SquiLu is full of hidden bugs and code note tested, I'm trying to bring tests to bring more confidence on both.
If someone already have any tests and want to share you are welcome !
Cheers !

**Comment by albertodemichelis** [comment]
pcall works as expected is the caller of the script that is raising the error. If that is not like lua, that's not a problem nor a bug.
