### ISSUE TITLE
Feature request: Testing of documentation source code

### ISSUE THREAD

**Issue by breakin** [albertodemichelis/squirrel#116]
To be very concrete I made a PR here https://github.com/albertodemichelis/squirrel/pull/115 to show how it could look like. It doesn't have to look exactly like that, feel free to come with suggestions.

What do you think? If you like whats in the PR I can do the work.

**Comment by mingodad** [comment]
If someone is interested I did ported some tests from Lua to SquiLu https://github.com/mingodad/squilu/tree/master/SquiLu/tests it can be ported to squirrel too with a bit of work.

**Comment by breakin** [comment]
@mingodad: Hi! I am pretty new to squirrel so I don't know how much it needs test. What I did find out is that the documentation has some errors and also was somewhat hard to read as a beginner.. So I wanted to do something around that. This suggestion is around testing the documentation so it matches squirrel, not squirrel itself (although it can be used like that a little bit).

**Comment by breakin** [comment]
I am closing the issue, lets keep discussion in PR #115.
