### ISSUE TITLE
convert this project from C++ to C

### ISSUE THREAD

**Issue by M1cha** [albertodemichelis/squirrel#13]
squirrel seems to be mostly C code anyway and this would allow us to use squirrel in embedded environments where C++ is not available.

If you're fine with this I'd even do that for you.

**Comment by M1cha** [comment]
I probably should have checked the header files. I didn't even know that you can have inheritance and public/private functions in structs.

This obviously makes things a lot more complicated.

**Comment by albertodemichelis** [comment]
Squirrel uses a subset of C++ with no exceptions, no dependencies of standard libs etc... that is available on every platform I've encountered so far. It also run on microcontrollers with 20kB of free RAM. This days there is really no reason to use pure C other than personal preference.

**Comment by M1cha** [comment]
"This days there is really no reason to use pure C other than personal preference."
this is not entirely true. in environments like bootloaders and kernel's you just don't have any c++ compilers or environment.
heck, on many systems you can't even use floating point.

but since this project seems to be heavily built with inheritance in mind, it doesn't sound like a option anyway since we probably want to stay compatible with older versions and don't want to completely rewrite squirrel.

**Comment by albertodemichelis** [comment]
I agree no C++ in kernels, even if it is possible if one wants to hurt himself. However no dynamic languages in kernels is also a good rule :) .

**Comment by M1cha** [comment]
I'm planning to use squirrel in UEFI :) UEFI does already support Python and Lua, but Squirrel looks A LOT better because it's python is way too heavy and thx to the C syntax Squirrel is easier to learn than  lua.

**Comment by M1cha** [comment]
I've successfully ported the C++ code to UEFI now :)
