### ISSUE TITLE
float does not conform to the IEEE-754 standard

### ISSUE THREAD

**Issue by oomek** [albertodemichelis/squirrel#131]
It seems like floats in Squirrel have some rounding/precision errors

```
print( 1080.0 * 0.025 + "\n" )
print( floor( 1080.0 * 0.025 ) + "\n" )
print( floor( 1080.0 / 40.0 ) + "\n" )

```
result:
27
26
27

expected result:
27
27
27

`print( format( "%.30f", 0.025) )`
returns:
0.024999998509883881
instead of:
0.02500000037252902984619140625

Can someone confirm it please.

**Comment by zeromus** [comment]
My results are
```
27
27
27
0.025000000372529029846191406250
```
Squirrel doesn't do floating math itself. It can't mess this up. Don't think it does the float formatting, either. This is affected by a setting in your compiler.

**Comment by oomek** [comment]
What kind of setting are you referring to? I use Squrrel to code themes in Attract Mode frontend.

**Comment by zeromus** [comment]
Floating point math, `-ffast-math`, etc. Also floating point environment settings determined by the process you've linked squirrel into, or maybe inherited from the parent environment. This is a general "why are my floating point precisions weird" problem you can ask the internet about without specifically asking about squirrel

**Comment by oomek** [comment]
Thanks for explaining, I found the compiler switches. I did not know how Squirrel handles math.
