### ISSUE TITLE
Squirrel performance

### ISSUE THREAD

**Issue by M1cha** [albertodemichelis/squirrel#14]
Out of curiosity I did a small performance test with squirrel and maybe you can tell me if either my code or the VM could be optimized:
C: http://pastebin.com/H5zsEi2h
SQ: http://pastebin.com/iFL1uWup

C: 0m5.714s
SQ: 2m19.643s, 1m1.179s with GCC's -O3

**Comment by albertodemichelis** [comment]
It seems about right on my PC  is 0m45.482s VC++ (Xeon E5-1650 v2 OC 4.4GHz)
You shouldn't compare an interpreted language with the fastest compiled language around.
Try comparing to Python,Ruby or such.
Anyway for best performances, remember to disable C++ exceptions, using GCC they burn 20/30% of CPU time(last time I tested).

**Comment by M1cha** [comment]
without exceptions: 0m57.665s
Well I just didn't think that the difference would be that big.

**Comment by albertodemichelis** [comment]
the you should disable exceptions in the CMake build :)

**Comment by albertodemichelis** [comment]
solved
