### ISSUE TITLE
Whitespace normalization

### ISSUE THREAD

**Issue by mfxmfx** [albertodemichelis/squirrel#15]
Please convert all source ode files to Unix EOF mode, strip trailing whitespace and expand all hard tabs (except in Makefiles and *.dsw).

Background: I just wanted to prepare a pull request only to realize that my editor has removed all trailing whitespace...

Thanks!
Markus

**Comment by albertodemichelis** [comment]
Ok, I'm new to Git. I'm fine solving the new line stuff. This means setting the autocrlf=true on windows machines and then remove and re-add every file right?

BTW, I like hard tabs.

**Comment by mfxmfx** [comment]
I respect your preferences, but in a shared development environment whitespace issues (line endings
and 4 vs. 8 spaces for a tab) are a continuous source of noise and merge conflicts. Apart from that
such a style can also be enforced on each commit by tools like Travis CI.

Please see my 2 commits (possible pull requrest) at

  https://github.com/mfxmfx/squirrel/commits/master

and tell me what you think.

~Markus

**Comment by albertodemichelis** [comment]
Ok, I thought about it, you convinced me :) . go ahead with a pull request.

Alberto

**Comment by mfxmfx** [comment]
Pull request created. I have working Travis-CI test scripts that could be added on top of that.

**Comment by mfxmfx** [comment]
Hi Alberto,

I have prepared Travis CI in a "travis" branch at

 https://github.com/mfxmfx/squirrel/commits/travis 

Please also browse the various build results at
 
   https://travis-ci.org/mfxmfx/squirrel

and tell me what you think.

~Markus

**Comment by albertodemichelis** [comment]
This is thought decision to make. I don't use and I don't like CMake. I'm ok to add a few files in the project because I understand that some people like it.
I cannot be the judge here, I want to bless 3.1 stable this week so if this is not solve the CMake files will remain what are now.
About Travis CI, as far as no files from Squirrel's sources are touched I can add a couple of .sh, but please leave the README alone.

**Comment by mfxmfx** [comment]
This issue is resolved and can be closed.
