### ISSUE TITLE
Feature Idea: modules

### ISSUE THREAD

**Issue by todace** [albertodemichelis/squirrel#165]
Lua have modules in standart library - https://www.lua.org/manual/5.3/manual.html#6.3
Modules helps in development and more - in code reusing.

**Comment by zeromus** [comment]
lua's modules are a terrible mess. a system tailored to your needs can be implemented nearly trivially, unless you are talking about all the dll garbage, which squirrel has no business doing. I'm glad squirrel doesn't do any of this. It clarifies its mission, unlike lua which suffers massively from an identity crisis.

**Comment by todace** [comment]
> lua's modules are a terrible mess. a system tailored to your needs can be implemented nearly trivially, unless you are talking about all the dll garbage, which squirrel has no business doing. I'm glad squirrel doesn't do any of this. It clarifies its mission, unlike lua which suffers massively from an identity crisis.

Well, just read manual of lua
No, I wasn't talking about cmodules (dll garbage).
Just squirrel modules.
And yes, it probably can be done nearly trivially - but this doesnt meant it is not useful.
Like classes in lua (and squirrel) can be done via tables and metamethods\delegates. But that doesnt means it is not useful that they are made in language itself (instead of creating them from the scratch all the time).
Well, standard library is something that is not mandatory to use - system or io is not part of language itself. I just suggested to have something in standard library - as this library is part of squirrel repository

**Comment by todace** [comment]
> lua's modules are a terrible mess. a system tailored to your needs can be implemented nearly trivially, unless you are talking about all the dll garbage, which squirrel has no business doing. I'm glad squirrel doesn't do any of this. It clarifies its mission, unlike lua which suffers massively from an identity crisis.

BTW - what is mission of squirrel and how it differs from lua mission?
Quote from official page:
>Squirrel is a high level imperative, object-oriented programming language, designed to be a light-weight scripting language that fits in the size, memory bandwidth, and real-time requirements of applications like video games.
>Squirrel is inspired by languages like Python,Javascript and especially Lua(The API is very similar and the table code is based on the Lua one)
> squirrel's syntax is similar to C/C++/Java etc... but the language has a very dynamic nature like Python/Lua etc... 

So I guess main idea is to have language like Lua, but with C++ syntax and with some extras like builtin classes and to be more strict (the last part is why I find Squirrel better than Lua) - like new slot in table with <- operator.
Well, a word for Bob Nystrom (he obviously has more expertise than me on making embeddable scripting languages)
http://wren.io/modularity.html

**Comment by zeromus** [comment]
Thanks for posting Bob Nystrom's arbitrary modules system. It's just one of many you could use as inspiration for what to make in squirrel. By contrast, almost every idea for how to implement classes in lua is terrible, and squirrel did it officially because there's really only one sensible way to want to do it, and it's better done in the language--and faster, too (uhhh probably). 

"Can be done trivially" is an argument for _not_ doing it in the language. It adds bloat and maintenance hazard in a project already progressing at a glacial pace. One should not do things simply because one can. 

What I would rather see is work on some more powerful features which would neither be trivial to implement in squirrel, nor performant, such as token filters or macros, which would enable you to create a syntax appropriate to your needs.

Since you asked, the way I see it, squirrel's mission is to be embedded in video games and be well-tolerated by a C++ programmer; lua is really confused about its mission, but things are generally mucked up by it being intended to be embedded but then that communication getting mixed up and people wanting to use it like python as a replacement for bash or perl. We don't need squirrel to join that party. Also lua's mission is to be as obnoxious as possible to a C++ programmer. Since you asked.

**Comment by todace** [comment]
> "Can be done trivially" is an argument for not doing it in the language. It adds bloat and maintenance hazard in a project already progressing at a glacial pace. One should not do things simply because one can

I generally completely agree with this statement.
But how is this applies to sqstdlib? 
endswith\startswith, lstrip\rstrip\strip are non-trivial? Split? Pow? Why are they important to be in stdlib (and some og them were not present in squirrel2 AFAIK) and modules are not?

> By contrast, almost every idea for how to implement classes in lua is terrible, and squirrel did it officially (I assume) because there's really only one sensible way to want to do it, and it's better done in the language--and faster, too (uhhh probably).
I don't think it is faster - and my tests shows that it is can even be slower.
And for sure there are more than one sensible way to do classes (while there are lots of ways to do that wrong), but to have it done one way in all places it is better (probably) to have it in language.
But why that doesnt apply to modules? I'm sure that there are a lot of ways to do them trivial and non trivial, wrong and messy or short and nice. But having them done one way as 'good example' but not mandatory (in stdlib) looks proper way to follow. There are reasons why classes probably cant be done in stdlib, but modules can.

**Comment by todace** [comment]
Squirrel is magnitudes less popular than lua. And that is in fact important from practical PoV - harder to find people familiar with (we find JS or Lua experienced), and impossible to find any appliable solution (practical things like url parsing, date parsing\printing, email parsing, tools likes linters or LPEG or some less common things like frp library). Some easiness with code reuse can be helplful I guess. 
We use squirrel instead of lua not because it has more clear mission (it doenst), not because it is faster (it is slower in most reasonable cases, if we not taking GC stop-the-world in account), or definitely not because we like c syntax so much (syntax is not importan at all, in most cases). And not because it is smaller - it is not, in any measurable way - code size, memory footprint, grammar.
We prefer Squirrel because it is stricter and safer to use as embeddable language from different points of view and in a lot of situations. 
BTW - +1 for this PR https://github.com/albertodemichelis/squirrel/pull/151 :)

**Comment by todace** [comment]
Hate GC also
You can get to any syntax.
assiging nil to slot is deletion, absent slot is nill, sparse arrays, any mistype table key creates key - is something that you can't just become used to. It just happens. All the time.

**Comment by mingodad** [comment]
Hello todace !
Maybe you could look at https://github.com/mingodad/squilu I'm trying to address several shortcomings in squirrel.
There is an attempt to bring modules to squirrel by https://github.com/pfalcon/squirrel-modules .
I have a distinct opinion about the direction of squirrel as a project.
Cheers !

**Comment by zeromus** [comment]
@todace, of course, those are many of the same syntaxes that make me want to kill myself. Whatever you want to call them. I can't separate the characters I type from the insane behaviours that follow, as easily as you can. All I know is does the language make me want to kill myself. I can't get used to any syntax, and I can't get used to any behaviours.

**Comment by todace** [comment]
> Hello todace !
> Maybe you could look at https://github.com/mingodad/squilu I'm trying to address several shortcomings in squirrel.
> There is an attempt to bring modules to squirrel by https://github.com/pfalcon/squirrel-modules .
> I have a distinct opinion about the direction of squirrel as a project.
> Cheers !

Squilu is something crazy from my perspective.
Language do not need 5 ways to declare local variable - 1 is enough. Having more keywords is worse than having less - it becomes harder to read code, harder to understand it, more time to get used to.
There is no value in supporting two languages (lua and squirrel) - you can always choose one. Less is more. Having two ways to do something is worse than to have one way.
Squirrel is very niche, by being almost as small as lua with different syntax and much less popular than lua\JS. It also doesnt have performance of lua. It is much less known than JS\python.
So it's niche is that it is almost as small as lua, and almost as performant as lua (but not even close to luajit - JIT is out of scope on ios\consoles), much smaller than JS or Python, and also much stricter.
What I think Squirrel needs is becoming more and more strict, allowing less errors that are found during Runtime and not during compilation. And performance optimizations, if they are not making it less simple to use, as it is always welcome on game development.
So from my POV - constant folding is welcome, double local variables, double constants  declarations and double slot in table declarations erorr are welcome - and we are using that.
Null propogation reduces cognitive complexity and make code simpler - https://docs.codeclimate.com/docs/cognitive-complexity - so they are also useful 
There are some other PRs here that I like (update of stdlib for example or add 'require' modules to stdlib)
I also think that squirrel can be changed even more to be more safe and useful, but these things are disccusible (and I don't think our good dictator - Alberto - is interested in future change\Squirrel3.2-4 or something, so I do not put them as suggestions here).
For example - change of filter\map\reduce (I think that underscore.js filter\map\reduce are mcuh more useful than current one, reduce at least needs default start value, for example, and map with reference to initial colllection is also not always useful, as well as without index). Someone can say that you can always make your own map\filter\reduce (as they did in underscore.js) - and yes, we did that.
However, having them built-in make things weird - it is not worse to have two ways to do something.
And of course having tool for AST-building and linter for Squirrel would be valuable, but this is out of scope of squirrel itself.

**Comment by todace** [comment]
> @todace, of course, those are many of the same syntaxes that make me want to kill myself. Whatever you want to call them. I can't separate the characters I type from the insane behaviours that follow, as easily as you can. All I know is does the language make me want to kill myself. I can't get used to any syntax, and I can't get used to any behaviours.
> 
> The form and the function are related, you know. Lua behaves weird because lua looks weird because lua is designed for aliens. Squirrel behaves less weird because squirrel looks less weird because squirrel is designed for C programmers.

@zeromus 14 years ago (and several versions of Squirrel ago also) I hated Lua and we migrated from Lua to Squirrel, because of reasons you are pointing.
However, years passed, I have seen LOTS of different alien things. I do not see Lua that alieny now )
Personally I prefer Python-like syntax, but I do not care that much :)
I still hate Luas GC, and some really dangerous design decisions, but I also understand how elegant it can be, something like very high-level assembler in world of dynamic embeddable scripting languages.
But I don't want to use assembler. Now Lua have linters, code analysys, Moonshine script (that compiles in lua but you can use much more sane syntax and much safer language - and sometimes it is faster). So nowdays lua 'eco-system' is much better and healthier than 14 years ago. But eco-system means something complex, and simplicity is better.

The only reason I'm looking in Lua nowdays as that it has much more code (and I prefer to to write code if it is possible), or because Lua (espically Luajit) in many cases has much more performance.
BTW Nan tagging can also be great idea for Squirrel to improve performance (but this is can brake some existing code if it was designed for 64bit integers on 64bit platforms).

**Comment by mingodad** [comment]
Thanks for the comments on SquiLu.
Putting our differences aside for a moment and talking about the similarities here are some points that I'm trying to address with SquiLu that I think enhance squirrel in no specific order:
- Sugar syntax for keys in tables it's nice "somettable_class.somekey = onevalue;" but it brings a chance for silly misspell  errors that could be prevented at compile time, I'm testing to have what I call "compile time string constants" actually I'm using the "$" sign like in shell/make to declare/use then:
```
const $one_name;
const $other_name;
local tbl = {};
tbl.$one_name <- 3;
tbl.$other_name <- 4;
local val = tbl.$one_name + tbl.$other_name;
local val2 = tbl.$one_name * tbl.$oter_name; //<<<< compile error $oter_name not declared
```
- The compiler has ways to emit warnings and I'm using it to warning when a inner scope variable is hiding an outer scope variable with the same name:
```
local myvar = 2;
{ //inner scope
  local myvar = 3; //<<< compile time warning local variable myvar shadow variable declared in outer scope
  ...
}
```
- I flag as an error trying to declare a variable more than once in the same scope:
```
local myvar = 4;
...
local myvar = "str"; //<<< compile time error attempt to declare an already declared variable 
```
- Add "#include, #define, #ifdef, #else, #endif" one pass compiler macros:
```
#ifdef __WIN32__
#include "win32.nut"
#else 
#include "generic.nut"
#endif
...
``` 
- Fixed the declaration of local functions to allow recursion:
```
local function fibo(n)
{
  if(n < 2) return 1;
  return fibo(n-2) + fibo(n-1); //<<< do not work in squirrel
}
```
- Exposed the lexer to scripts, would be nice to expose the AST but for now this is easy:
```
var fd = file("lexer.nut", "r");
local txt = fd.read(fd.len());
fd.close();

var lex = new SQLexer(txt);

local first_enum_token = lex.first_enum_token();
local last_enum_token = lex.last_enum_token();
print(first_enum_token, last_enum_token);

var gconstants = getconsttable();
for(var i=first_enum_token+1; i < last_enum_token; ++i)
{
	var tkname = lex.token_name(i);
	table_rawset(gconstants, tkname, i);
	print(tkname, i);
}


var tok =  lex.lex();
while(tok > 0) {
	local tkstr;
	if(tok > first_enum_token) tkstr = lex.tok2str(tok);
	else tkstr = tok.tochar();
	print(
		tok,
		tkstr,
		lex.token_name(tok),
		lex.svalue(),
		lex.currentline(),
		lex.currentcolumn()
		);
	tok = lex.lex();
	/*
	if(tok == TK_CLASS)
	{
		print("class found");
	}
	*/
}
```
- Added an option to export commented opcode for a script with the idea to do some optimisations:
```
squilu -s test-set-global.nut
```
```
global <- 0;
class Test {
  static function Go() {
    print(global + "\n");
    global = 1;
    print(global + "\n");
  }
}
Test.Go();
```
```
local bytecode = {
	source_name = "test-set-global.nut",
	function_name = "main",
	function_return_type = null,
	literals = [
		/*0*/ "global",
		/*1*/ "Test",
		/*2*/ "Go",
	],
	parameters = [
		/*0*/ "this",
		/*1*/ "vargv",
	],
	outervalues = [
		//[type, src, name],
	],
	localvarinfos = [
		//[pos, name, start_op, end_op, scope, type, type_name, dtype_name],
		/*0*/ [0, "this", 0, 12, 1, 1, "ANY", ""],
		/*1*/ [1, "vargv", 0, 12, 1, 1, "ANY", ""],
	],
	lineinfos = [
		//[op, line],
		/*0*/ [0, 1], /*_OP_LOAD*/
		/*1*/ [3, 2], /*_OP_LOAD*/
		/*2*/ [9, 9], /*_OP_GETK*/
	],
	defaultparams = [],
	instructions = [ /*stack*/
		//[op_str, op, arg0, arg1, arg2, arg3],
		/*0*/ ["_OP_LOAD", 1, 2, 0, 0, 0],		/* stk[2] <- literals[0]("global") */
		/*1*/ ["_OP_LOADINT", 2, 3, 0, 0, 0],	/* stk[3] <- arg1(0) */
		/*2*/ ["_OP_NEWSLOT", 11, 255, 0, 2, 3],	/* flags(255), table_at_stk(0),  key_at_stk(2), val_at_stk(3) */
		/*3*/ ["_OP_LOAD", 1, 2, 1, 0, 0],		/* stk[2] <- literals[1]("Test") */
		/*4*/ ["_OP_NEWOBJ", 33, 3, -1, 255, 2],	/* stk[3], len(-1), NOT_CLASS(2) */
		/*5*/ ["_OP_LOAD", 1, 4, 2, 0, 0],		/* stk[4] <- literals[2]("Go") */
		/*6*/ ["_OP_CLOSURE", 48, 5, 0, 0, 0],	/* stk_at_arg0[5] <- functions[0]("Go"), isLanbda(0) */
		/*7*/ ["_OP_NEWSLOTA", 58, 2, 3, 4, 5],	/* flags(2), table_at_stk(3),  key_at_stk(4), val_at_stk(5) */
		/*8*/ ["_OP_NEWSLOT", 11, 2, 0, 2, 3],	/* flags(2), table_at_stk(0),  key_at_stk(2), val_at_stk(3) */
		/*9*/ ["_OP_GETK", 9, 2, 1, 0, 0],		/* stk[2] <- literals[1]("Test") */
		/*10*/ ["_OP_PREPCALLK", 8, 2, 2, 2, 3],	/* closure_at_stk[2], stk[2].get(literals[2]) -> stk[3] */
		/*11*/ ["_OP_CALL", 6, 255, 2, 3, 1],		/* target[255], lvi[2]("?"), stackbase(3), nargs(1) */
		/*12*/ ["_OP_RETURN", 23, 255, 0, 0, 0],	/* _arg0(255) != 255 ? stk[0] : null */
	],
	functions = [
/*function 0*/{
	source_name = "test-set-global.nut",
	function_name = "Go",
	function_return_type = null,
	literals = [
		/*0*/ "print",
		/*1*/ "global",
		/*2*/ [==[
]==],
	],
	parameters = [
		/*0*/ "this",
	],
	outervalues = [
		//[type, src, name],
	],
	localvarinfos = [
		//[pos, name, start_op, end_op, scope, type, type_name, dtype_name],
		/*0*/ [0, "this", 0, 13, 1, 1, "ANY", ""],
	],
	lineinfos = [
		//[op, line],
		/*0*/ [0, 3], /*_OP_PREPCALLK*/
		/*1*/ [0, 4], /*_OP_PREPCALLK*/
		/*2*/ [5, 5], /*_OP_LOAD*/
		/*3*/ [8, 6], /*_OP_PREPCALLK*/
		/*4*/ [13, 7], /*_OP_RETURN*/
	],
	defaultparams = [],
	instructions = [ /*stack*/
		//[op_str, op, arg0, arg1, arg2, arg3],
		/*0*/ ["_OP_PREPCALLK", 8, 1, 0, 0, 2],	/* closure_at_stk[1], stk[0].get(literals[0]) -> stk[2] */
		/*1*/ ["_OP_GETK", 9, 3, 1, 0, 0],		/* stk[3] <- literals[1]("global") */
		/*2*/ ["_OP_LOAD", 1, 4, 2, 0, 0],		/* stk[4] <- literals[2]("
") */
		/*3*/ ["_OP_ADD", 17, 3, 4, 3, 0],		/* stk[3] = stk[4]("?") + stk[3]("?") */
		/*4*/ ["_OP_CALL", 6, 255, 1, 2, 2],		/* target[255], lvi[1]("?"), stackbase(2), nargs(2) */
		/*5*/ ["_OP_LOAD", 1, 1, 1, 0, 0],		/* stk[1] <- literals[1]("global") */
		/*6*/ ["_OP_LOADINT", 2, 2, 1, 0, 0],	/* stk[2] <- arg1(1) */
		/*7*/ ["_OP_SET", 13, 255, 0, 1, 2],	/* stk_at_arg1[0].set(stk_at_arg2(1), stk_at_arg3(2)) */
		/*8*/ ["_OP_PREPCALLK", 8, 1, 0, 0, 2],	/* closure_at_stk[1], stk[0].get(literals[0]) -> stk[2] */
		/*9*/ ["_OP_GETK", 9, 3, 1, 0, 0],		/* stk[3] <- literals[1]("global") */
		/*10*/ ["_OP_LOAD", 1, 4, 2, 0, 0],		/* stk[4] <- literals[2]("
") */
		/*11*/ ["_OP_ADD", 17, 3, 4, 3, 0],		/* stk[3] = stk[4]("?") + stk[3]("?") */
		/*12*/ ["_OP_CALL", 6, 255, 1, 2, 2],		/* target[255], lvi[1]("?"), stackbase(2), nargs(2) */
		/*13*/ ["_OP_RETURN", 23, 255, 0, 0, 0],	/* _arg0(255) != 255 ? stk[0] : null */
	],
	functions = [
	],
	stacksize = 5,
	bgenerator = 0,
	varparams = 0,
},
	],
	stacksize = 6,
	bgenerator = 0,
	varparams = 1,
}
```
- Moved all table functions to globals, allowing any key to be used:
```
local tbl = {};
table_rawset(tbl, "key", "value");
local v = table_rawget(tbl, "key2", "default_value");
print(table_len(tbl));
```
- Added the controverted "goto".
- Added string handling like in lua so we can read/write/print/... like in lua (char only).
- Fixed several bugs in regexp (not yet fixed in squirrel for no apparent reason) and added lua pattern matching find/match/gmatch/gsub.
- Added multiline strings with lua separators "[==[]==]", C++ separators, adjacent strings merged at compile time, strings with line continuation.
-  Class declaration can use class name as constructor function.
- Function/variables can be declared like Javascrip/Typescript/C/C++ (discarded at compile time for now).
- Added "typdef" to declare alias names similar to C/C++.
...
The overall idea always was to improve things (although that can be and frequently are questioned).
Cheers !

**Comment by IngwiePhoenix** [comment]
Hello!

What's module support looking like right now? I'd like to use Squirrel in favor of Lua, since I prefer myself a C/C++-ish syntax. But I do need module support, so I was curios to hear what this issue's status is like, right now.

Thanks. :)

**Comment by zeromus** [comment]
status is no change

**Comment by jsProj** [comment]
There is this which provides a require system just from importing a single.
[Squirrel Require](https://github.com/inlife/squirrel-require)

**Comment by jsProj** [comment]
> Hello!
> 
> What's module support looking like right now? I'd like to use Squirrel in favor of Lua, since I prefer myself a C/C++-ish syntax. But I do need module support, so I was curios to hear what this issue's status is like, right now.
> 
> Thanks. :)

[Squirrel Require](https://github.com/inlife/squirrel-require)

**Comment by todace** [comment]
> Hello!
> 
> What's module support looking like right now? I'd like to use Squirrel in favor of Lua, since I prefer myself a C/C++-ish syntax. But I do need module support, so I was curios to hear what this issue's status is like, right now.
> 
> Thanks. :)

Done also in our fork of squirrel https://github.com/GaijinEntertainment/quirrel

**Comment by inlife** [comment]
Very late and very shameless plug, but might be relevant to the conversation: https://github.com/inlife/squirrel-require
