### ISSUE TITLE
Pointer overflow in SQVM::IsFalse() function

### ISSUE THREAD

**Issue by oomek** [albertodemichelis/squirrel#171]
Sometimes `SQVM::IsFalse()` hangs our app and when I print the content of `&o` it returns `0xFFFFFFFFFFFFFF0`
Seems like a pointer overflow to me. It's completely random, and only happens when the application starts. it crashes in 20% of cases, sometimes more often.

**Comment by oomek** [comment]
The freeze originates from
```
try
{
	Function &func = (*itr)->get_fn();
	if ( !func.IsNull() )
	{
		keep = func.Evaluate<bool>(
			(int)t,
			var,
			ttimer.getElapsedTime().asMilliseconds() );
	}
}
catch( Exception &e )
{
	FeLog() << "Script Error in transition function: " << (*itr)->m_fn
			<< " - " << e.Message() << std::endl;
}
```
in our code the func.evaluate never returns

**Comment by zeromus** [comment]
I don't think any of the information you provided is going to be very helpful in understanding the problem. you need to try stripping down your script and simplifying your engine code a bit at a time.

it shouldn't be random unless you're doing something pretty odd, depending on the system timer in your code or script; OR unless youve selected address space layout randomization in your build options. I suggest disabling that and you may get more consistent results for debugging.

**Comment by oomek** [comment]
If you mean `-fno-stack-protector` then no, it's not in the cflags. Our app is cross-compiled for Win32 in Ubuntu with MXE

**Comment by oomek** [comment]
Is there any information I could provide, that would help narrowing the problem?

**Comment by zeromus** [comment]
You would need to make sure it's not getting linked with --dynamicbase passed to the linker. you would probably know if the dynamic base is getting used by doing a printf("%p",malloc(1)) immediately in main. making sure that's deterministic is first step to getting deterministic debugging.

narrowing the problem is up to you. like i said, strip down your script and host. especially remove any logic related to the system time. you want it to be 100% reproducible.

**Comment by oomek** [comment]
I've checked, this flag is not specified anywhere. printf("%p",malloc(1)) returns a random hex number every time. Surprisingly, setting the compatibility flag to Windows 8 or lower, eliminates the overflows and the app runs normally 100% of the time. (I'm on Win10)

**Comment by zeromus** [comment]
That's unfortunate. It'd be better if it crashed 100% of the time. You may try adding a bunch of jumbledy allocs at the beginning of the program to get the heap into a vastly different state (allocate 100s of MB if you can). It's also possible the problem has nothing to do with the base address and the compatibility flag affected it for other reasons (but I doubt it)

**Comment by oomek** [comment]
I'll try to find a way to make it crash 100% of the time then I'll come back. I'll also try what you suggested. Thanks.

**Comment by zeromus** [comment]
OK, but after you get it to crash 100% of the time, the next step is still yours: start stripping things down until you better understand the true origin of the problem, or else have a ridiculously tiny test case that malfunctions for no apparent reason

Also, I don't know what a "pointer overflow" is but to me it looks more like something got a null ptr and then something else tried to subtract 0x10 from it. most likely an error in sqrat (possibly a sqrat user error) and not squirrel. Also your pointer `0xFFFFFFFFFFFFFF0` is weird; it's one nybble shorter than I would expect. I suppose you transcribed it wrongly.

**Comment by oomek** [comment]
Stripping down will be tricky as it's about 100,000 lines of code :) And you are right, now the pointer passed to isFalse() is different.
```
0xd6b5200
0xd6b5200
0xd6b51d0
0xd74ce40
0xd6b5210
0xd6b5250
0xd6b5250
0xd6b5250
0xd6b5250
0xd6b5260
0xd6b5380
0xd6b5380
0xd6b5260
0xd74ce40
0xd6b51d0
0xd6b51d0
0x1bc6b7b0 <- here it crashes
```

**Comment by zeromus** [comment]
yes, it will be tricky
you must be using %x for your pointer debug prints. use %08x or %016x instead

**Comment by oomek** [comment]
The same thing with %016x. Just more zeroes
```
000000000d762210
000000001bc6b7b0
```

**Comment by zeromus** [comment]
Thank you. Now we know you aren't making copy/paste errors resulting cropping nybbles off the pointer values

**Comment by rversteegen** [comment]
Since you are crosscompiling, does that mean you also have a Linux port of your program? If so, run it under valgrind. Regardless of whether it actually crashes on Linux, valgrind is very helpful for finding memory errors.
