### ISSUE TITLE
sphinx.ext.pngmath has been removed

### ISSUE THREAD

**Issue by FabianWolff** [albertodemichelis/squirrel#176]
In [`doc/source/conf.py`](https://github.com/albertodemichelis/squirrel/blob/780e9c96b34d24d347c90756efa96f2927fcb641/doc/source/conf.py#L32), there is currently this piece of code:
```
extensions = [
    'sphinx.ext.pngmath',
]
```
This is problematic because the pngmath extension has [been removed](https://github.com/sphinx-doc/sphinx/pull/4702) from Sphinx, which has already caused the Debian Squirrel package to [fail to build](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923012). The 3.1 stable release of Squirrel did not even use any of the extension's features, so a solution could be to just remove `sphinx.ext.pngmath` from the `extensions` list in `doc/source/conf.py`. I haven't verified that this still works in the current development version of Squirrel; if not, I believe the pngmath Sphinx extension has been replaced by the imgmath extension, so perhaps one would have to look there for a replacement.

Thanks,
Fabian

**Comment by albertodemichelis** [comment]
I think it can be removed. It is not used.

Alberto

**Comment by albertodemichelis** [comment]
fixed
