### ISSUE TITLE
local scope issue in closure after yield

### ISSUE THREAD

**Issue by jayeheffernan** [albertodemichelis/squirrel#178]
I've found some unexpected behaviour, I think it's a bug.  It's to do with the way locally scoped variables are handled inside closures that are defined inside generators, after the generator has yielded... what a mouthful!  Examples should make it clearer.

### Minimal Example

The closure has a reference to the local variable, which works until after the generator `yields`.  After that the closure still has the name of the local variable in scope; it will not crash attempting to access , but I have confirmed that it does crash if trying to access some other, never-defined variable e.g. `myUndeclaredVariable`.  Despite the fact that the local variable seems to be in scope for the closure, the value of the variable is erroneously reported as `null`.

#### Code

```
function generate() {
    local myLocalVariable = "my local variable";
    local logIt = function() {
        print("myLocalVariable: " + myLocalVariable + "\n");
    };
    logIt();
    yield 1;
    logIt();
}

// Step through the generator
foreach (f in generate()) { };
```

#### Expected Output

```
myLocalVariable: my local variable
myLocalVariable: my local variable
```

#### Actual Output

```
myLocalVariable: my local variable
myLocalVariable: (null : 0x0x0)
```

### Extended Example

This extended example narrows down the scope of the issue.  Firstly, by running the closure twice in a row we see that it retains a working reference to the variable across multiple calls, just not across a `yield`.  Secondly, by logging the variable from the top scope of the generator, we see that the reference to the variable in the scope of the generator still works correctly (and has not been somehow set to `null`), even after the `yield`.  Lastly, by defining a second (near-identical) closure later on, we see that a new closure can be given a working reference to the variable even after a `yield`, which will continue to work properly until the next `yield`.

#### Code

```
function generate() {
    local myLocalVariable = "my local variable";
    local logIt = function() {
        print("(logIt) myLocalVariable: " + myLocalVariable + "\n");
    };

    print("(generate) myLocalVariable: " + myLocalVariable + "\n");
    logIt();
    logIt();
    yield 1;
    logIt();
    print("(generate) myLocalVariable: " + myLocalVariable + "\n");

    local logIt2 = function() {
        print("(logIt2) myLocalVariable: " + myLocalVariable + "\n");
    };

    logIt2();
    logIt2();
    yield 1;
    logIt2();
    print("(generate) myLocalVariable: " + myLocalVariable + "\n");
}

// Step through the generator
foreach (f in generate()) { };
```

#### Expected Output

```
(generate) myLocalVariable: my local variable
(logIt) myLocalVariable: my local variable
(logIt) myLocalVariable: my local variable
(logIt) myLocalVariable: my local variable
(generate) myLocalVariable: my local variable
(logIt2) myLocalVariable: my local variable
(logIt2) myLocalVariable: my local variable
(logIt2) myLocalVariable: my local variable
(generate) myLocalVariable: my local variable
```

#### Actual Output

```
(generate) myLocalVariable: my local variable
(logIt) myLocalVariable: my local variable
(logIt) myLocalVariable: my local variable
(logIt) myLocalVariable: (null : 0x0x0)
(generate) myLocalVariable: my local variable
(logIt2) myLocalVariable: my local variable
(logIt2) myLocalVariable: my local variable
(logIt2) myLocalVariable: (null : 0x0x0)
(generate) myLocalVariable: my local variable
```

I've also played around with adding `.bindenv()` calls in different places and with different values, but I haven't found any combinations that behave any differently.

**Comment by albertodemichelis** [comment]
mmh, That's a bug, I'll investigate, thank you.

**Comment by albertodemichelis** [comment]
Fixed. Now yield will "close" any free variable in the generator, at the moment seems to be the only possible solution.

**Comment by jayeheffernan** [comment]
That's fixed it, I get expected output for both cases.  Thanks!
