### ISSUE TITLE
Cannot build on FreeBSD

### ISSUE THREAD

**Issue by comarius** [albertodemichelis/squirrel#193]
Hi,
I got errors on feeBSD

`1 warning generated.
In file included from sqvm.cpp:5:
In file included from /usr/include/c++/v1/math.h:310:
/usr/include/c++/v1/limits:150:85: error: expected expression
    _LIBCPP_INLINE_VISIBILITY static _LIBCPP_CONSTEXPR type min() _NOEXCEPT {return type();}
then more
`

**Comment by comarius** [comment]
Got it: @ 
sqvm.cpp
`
#undef type
#       include <math.h>
#define type(obj) ((obj)._type)

`

**Comment by zeromus** [comment]
IMO this bug is worth leaving open. Squirrel should not be using a macro like that, it's too fragile.

**Comment by comarius** [comment]
Ok,
Looks like is a conflict between  defining a token like  'type' and the std library type() function.

**Comment by albertodemichelis** [comment]
This was fixed a while ago and renamed sq_type(). Did we miss something?

**Comment by comarius** [comment]
I have a very old versiosn of squirrel. Ill update
