### ISSUE TITLE
Source files have mixed CR/LF

### ISSUE THREAD

**Issue by mingodad** [albertodemichelis/squirrel#2]
Hello !
I noticed that the source files (also makefiles, ...) have a mix of CR/LF and this will lead to making comparing files, sbmit pulls, ... a bit hard.
Because this repository is new (has few commits/history) would be nice to clean then and stick with one line end termination. Also several lines have spaces at the end.

My vote is to have all source files ending on LF alone.

Cheers !

**Comment by mingodad** [comment]
I've been looking again in the source code and it's all lines end in CR/LF, it's on my side the problem I'm using linux and my editor tend to only use LF.

**Comment by albertodemichelis** [comment]
I'll look into this.
