### ISSUE TITLE
Refactoring delegates

### ISSUE THREAD

**Issue by mingodad** [albertodemichelis/squirrel#20]
Hello !
In SquiLu (https://github.com/mingodad/squilu) I'm trying to change the way delegates are set/get with the actual implementation inherited from squirrel there is some drawbacks like delegate methods overwrite. I'm testing with an empty delegate_table as default delegate for tables and it almost work except for userdata.tostring() right now, so I created a global try_tostring(obj, default_str).

But still the other delegate methods "_add, _sub, ..." can be accidentally overwritten lua uses two underscores to try make it more unlikely to be overwritten.

Does anyone have any other idea about how to solve the overwrite problem ?

The commit that does it is this one https://github.com/mingodad/squilu/commit/6941aeae44340ddf240615dc24f56f299c1d6e23

Cheers !

**Comment by albertodemichelis** [comment]
nop
