### ISSUE TITLE
how to compile on wiodnows

### ISSUE THREAD

**Issue by ufoul** [albertodemichelis/squirrel#210]
do make or what i did make and it says
`$ make
mkdir -p lib
A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file lib already exists.
Error occurred while processing: lib.
mkdir -p bin
A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file bin already exists.
Error occurred while processing: bin.`
and im in the directory what do i do
also i meant build im trying to build from source

**Comment by RobLoach** [comment]
If you get cmake running on windows... it's over at:
https://github.com/albertodemichelis/squirrel/blob/master/COMPILE#L26
