### ISSUE TITLE
Did I disprove the theory?

### ISSUE THREAD

**Issue by ondkeso** [albertodemichelis/squirrel#212]
I manage to assert false in the destructor of SQSharedState where it states:
https://github.com/albertodemichelis/squirrel/blob/cd6f60867717f84bb3cf913c0c4000279f1ff789/squirrel/sqstate.cpp#L198

**Comment by rversteegen** [comment]
...how?

**Comment by ondkeso** [comment]
Hmmm, sadly I'm guessing nothing was proved. We had some other issues at the time which seemed to boil down to unsafe multithreading, so that probably borked up the gc chain somehow.
Though I do wonder what theory is proved by that assert. The code just below suggests that there used to be additional gc cleaning required which is now unnecessary, or rather we'd assert false if the additional cleaning is still needed. Any thoughts @rversteegen?

**Comment by albertodemichelis** [comment]
Yep, that theory seems to be correct. I never managed to break it... but you never know.
