### ISSUE TITLE
Class declaration do not check for duplicates

### ISSUE THREAD

**Issue by mingodad** [albertodemichelis/squirrel#24]
Hello !
Squirrel do not check for duplicates in class declarations see example bellow that compiles without errors:
```
class K
{
	v1 = 0;
	v1 = 0;
	v2 = 0;
	
	function f1(){}
	function f1(){}
}
```

**Comment by mingodad** [comment]
SquiLu has fixed this and expanded the subset of C/C++ accepted syntax  see this commit:
https://github.com/mingodad/squilu/commit/c6444139df1499669b300accc415dbd9a2b857c9

**Comment by albertodemichelis** [comment]
because classes "newmember" can be trapped by _newmember, this is a desirable sideffect. I use it in our engine for implementing remote procedure call.

**Comment by mingodad** [comment]
Good point but it checking it at compile time do not break what you describe at runtime, and from the syntax and logic point of view it's an error declare more than one member with the same name, what will be the result of call to that member name ?

Cheers !

**Comment by mingodad** [comment]
Can you give your opinion about accepting a bigger subset of C/C++ in SquiLu, what would be the downsides ?
What can be improved ?
Probably SquiLu will end up trying to do something similar with https://github.com/zdevito/terra, using llvm as backend (fat squirrel as you mentioned before).
Cheers !

**Comment by mingodad** [comment]
Also related to this bug, try this example:
```
class K
{
  v1=0;
}
local k = K();
print(k.v1);

class K2
{
  v1=0;
  v1=0;
}
local k2=K2();
print(k2.v1);
```

**Comment by albertodemichelis** [comment]
Well "terra" seems to be a quite different language than lua. The syntax is similar but looks like quite a big effort, it's like writing a C++ like language that spits out lua native closures.I must admit it is interesting but to make it into something useful you need debuggers and ide support. That would be my biggest concern, looks like a huge effort.
About member shadowing; it is a choice, I use this semantic if few places in my projects, it has never been a problem. I think even C++ allows shadowing of members in child classes, it is nothing new.

**Comment by mingodad** [comment]
Yes C++ allow shadow of members on child classes but not int class itself.

**Comment by mingodad** [comment]
Fixing this in SquiLu I found a piece of code I have with a big class where I had one member function defined twice (an error).
Cheers !

**Comment by mingodad** [comment]
I do not think that it's a good idea leave this issue as it is !
This will give headaches for squirrel users, debugging their code !
Cheers !
