### ISSUE TITLE
Weakref question ?

### ISSUE THREAD

**Issue by mingodad** [albertodemichelis/squirrel#25]
Hello !
I we insert a weakref on the registry table it's removed automatically when the object is released ?
Example:
```
static SQRESULT sq_obj_releasehook(SQUserPointer p, SQInteger size)
{
    if(p)
    {
            sq_free(p, size); //no need to do anything with registrytable ?
    }
    return 0;
}

static SQRESULT sq_obj_constructor(HSQUIRRELVM v)
{
    void *obj = sq_malloc(sizeof(obj_size));
    memset(obj, 0, sizeof(obj_size));
    //setup obj
   ...
    sq_setinstanceup(v, 1, obj);
    sq_setreleasehook(v,1, sq_obj_releasehook);
   
    //save a weakref to allow statement return it's db
    sq_pushstring(v, _SC("obj_key") );
    sq_weakref(v, 1);
    sq_setonregistrytable(v);
    return 1;
}
```
Cheers !

**Comment by albertodemichelis** [comment]
yes, the weak reference will be "nulled". Be aware that the actual wakreference object will still be in the registry, and you must check for null with sq_getweakrefval().

**Comment by mingodad** [comment]
So we need to manually remove the weakreference object ?

**Comment by mingodad** [comment]
For one extension I need something like the code bellow to remove a weakreference from inside a releasehook, right now when I try to remove it using the stack I get double call to the releasehook handler (when I push the registry key it overwrite thestack been released and double free happens).
Removing the weakreference is enough or I also need to call it's destructor ?
Cheers !
```
SQRESULT sq_delete_on_registry_table(HSQUIRRELVM v, SQUserPointer uptr)
{
    SQObjectPtr key = uptr;
	if(type(key) == OT_NULL) {
		return sq_throwerror(v, _SC("null key"));
	}
    _table(_ss(v)->_registry)->Remove(key);
    return SQ_OK;
}

////trouble code where I want to use the above
struct some_extension_st
{
	SomeObjec *obj;
	HSQUIRRELVM v;
	HSQOBJECT cb;
}
static SQRESULT sq_some_release(SQUserPointer p, SQInteger size)
{
	some_extension_st *obj = (some_extension_st*)p;
	if(obj)
	{
		//remove waekref from registrytable
		sq_pushregistrytable(p->v); //here we enter a loop that call us again
		sq_pushuserpointer(p->v, p->obj); //p->obj is the key
		sq_deleteslot(p->v, -2, SQFalse);
		sq_poptop(p->v);
		
		sq_release(p->v, &p->cb);
		...
		sq_free(p, sizeof(*p));
	}
}
```

**Comment by mingodad** [comment]
By the way would be nice to have a C++ interface to squirrel/squilu without need go through the C api, squirrel as C++ library. The  C api do a lot of turns that C++ do not need.
Cheers !

**Comment by mingodad** [comment]
Ok I followed the code in "_table(_ss(v)->_registry)->Remove(key);" and it does call .Null() on the object removed.
Thanks !

**Comment by mingodad** [comment]
Hello again !
Using the function bellow I discovered that when we close squirrel/squilu vms they call release hooks and the registry is already NULL.
Is this a bug ?
Cheers !
```
SQRESULT sq_delete_on_registry_table(HSQUIRRELVM v, SQUserPointer uptr)
{
    SQObjectPtr key = uptr;
	if(type(key) == OT_NULL) {
		return sq_throwerror(v, _SC("null key"));
	}
	SQTable *registry = _table(_ss(v)->_registry);
    if(registry) //when closing the vm releasehooks are called with NULL registry
    {
        registry->Remove(key);
        return SQ_OK;
    }
    return SQ_ERROR;
}
```

**Comment by albertodemichelis** [comment]
I don't understand what you mean. That code is not from squirrel's vm.

**Comment by albertodemichelis** [comment]
I think I understand, when a vm is finalized all tables are cleared. Probably that's why the registry is already empty.
