### ISSUE TITLE
quirrel failed to compile on msys2

### ISSUE THREAD

**Issue by iahung** [albertodemichelis/squirrel#260]
I don't know if posting here is right or not but [quirrel](https://github.com/GaijinEntertainment/quirrel) doesn't enable issues page on their repository so I posted here anyway. This original squirrel compiled fine on msys2.

p/s: by msys2 I means the mingw64 shell.

**Comment by VasiliyRyabtsev** [comment]
I have enabled issues section, please feel free to post there https://github.com/GaijinEntertainment/quirrel/issues.
