### ISSUE TITLE
Documentation of sq_instanceof is wrong

### ISSUE THREAD

**Issue by habi498** [albertodemichelis/squirrel#263]
> Returns: | SQTrue if the instance at position -2 in the stack is an instance of the class object at position -1 in the stack.

But in sq_api.cpp, i find that
`
SQBool sq_instanceof(HSQUIRRELVM v)
{
    SQObjectPtr &inst = stack_get(v,-1);  
    SQObjectPtr &cl = stack_get(v,-2);
`

So instance must be at position -1 and class must be at -2. Please correct the documentation if possible.

**Comment by albertodemichelis** [comment]
fixed

**Comment by habi498** [comment]
Thanks for fixing it in github. I hope it will be fixed in the online reference manual too.
