### ISSUE TITLE
local table = dofile("file.json") possible?

### ISSUE THREAD

**Issue by oomek** [albertodemichelis/squirrel#272]
Is there an easy way of directly loading a pure JSON file like the ones that are generated by Github API?
When I use `dofile()` Squirrel requires that the file file starts with `return` keyword.

**Comment by albertodemichelis** [comment]
No Sorry :)

**Comment by oomek** [comment]
Oh well, nevermind then, I'll stick on manually parsing the file then. Thanks for answering.
