### ISSUE TITLE
Squirrel do not accept functions on for loop

### ISSUE THREAD

**Issue by mingodad** [albertodemichelis/squirrel#29]
Hello !
Trying to parse/run a subset of C/C++ code with SquiLu I could get almost all the squirrel/squilu compiler C++ code parsed and one of the things that didn't parsed was this:
```
    void CommaExpr(bool warningAssign=false)
    {
        for(Expression(warningAssign); _token == ','; _fs->PopTarget(), Lex(), CommaExpr(warningAssign));
    }
```
Cheers !

**Comment by albertodemichelis** [comment]
no idea what this means, seems unrelated to Squirrel.

**Comment by mingodad** [comment]
Look at this http://www.zentut.com/c-tutorial/c-for-loop/
It means that this doesn't work on squirrel:
```
function doSomething(){}
function testCondition(){return maybeTrue;}
function doAnotherThing(){}

for(doSomething(); testCondition(); doAnotherThing());
```

**Comment by albertodemichelis** [comment]
works for me
  function doSomething(){print("something\n");}
  local x = 0;
  function testCondition(){x ++; return x % 10 != 9;}
  function doAnotherThing(){print("another thing\n");}
  
  for(doSomething(); testCondition(); doAnotherThing());

**Comment by mingodad** [comment]
Sorry and thanks !
You are right !
I did changes to the parser/compiler to accept C/C++ style declarations and I was accepting IDENTIFIERS the same as local declarations and realized later on when trying to run this javascritpt :
https://github.com/albertodemichelis/squirrel/issues/29#issuecomment-218533079
After your answer I found and fixed it in SquiLu.
Again thanks and sorry !
