### ISSUE TITLE
Missing raw document files

### ISSUE THREAD

**Issue by mingodad** [albertodemichelis/squirrel#3]
Hello !
I noticed that the raw document files are missing (the ones you use to generate pdf/chm), if we have then here will be easier to contribute to then.

Cheers !

**Comment by albertodemichelis** [comment]
The doc pipeline is a bit peculiar. It's a mix of xmls(custom format) that gets formatted by custom xslt stylesheets and then passed into a docbook stylesheet. It is something that should probably be converted in something more modern and with less dependencies and possibly have its own repo.

**Comment by mingodad** [comment]
Hello !
For documentation I think this can be a good option: https://github.com/fadado/literate
Cheers !

**Comment by albertodemichelis** [comment]
I added the new doc sources
