### ISSUE TITLE
Weird code in sq_setreleasehook and sq_getreleasehook

### ISSUE THREAD

**Issue by zeromus** [albertodemichelis/squirrel#36]
Why do these functions check sq_gettop()? They don't care about the structure of the stack. Based on my research this used to check for a stack size in excess of 2 a few versions ago (don't understand the purpose of that) and from there it went all the way back to the first squirrel version.

There don't seem to be any other functions doing similar checks; I imagine this was detritus from an early version of squirrel which had sq_set/get releasehook operating on the stack top instead of a given index?

I think the checks should simply be removed.

example:

```
void sq_setreleasehook(HSQUIRRELVM v,SQInteger idx,SQRELEASEHOOK hook)
{
//    if(sq_gettop(v) >= 1) //needless
{
        SQObjectPtr &ud=stack_get(v,idx);
        switch( type(ud) ) {
        case OT_USERDATA:   _userdata(ud)->_hook = hook;    break;
        case OT_INSTANCE:   _instance(ud)->_hook = hook;    break;
        case OT_CLASS:      _class(ud)->_hook = hook;       break;
        default: break; //shutup compiler
        }
    }
}
```

**Comment by albertodemichelis** [comment]
yep that's unnecessary
