### ISSUE TITLE
Where are automatic tests?

### ISSUE THREAD

**Issue by Darelbi** [albertodemichelis/squirrel#41]
I want to test it with my compilers  (GCC 4.0 up to GCC 5.2). Thanks

**Comment by albertodemichelis** [comment]
you mean regression tests?

**Comment by Darelbi** [comment]
Yes, any kind of test related to squirrel, I just need it because of my workflow

**Comment by zeromus** [comment]
Automatic tests are in the brain of guy who first needs automatic tests. Happy coding!

**Comment by paulsapps** [comment]
I guess this means there are none?

**Comment by zeromus** [comment]
Gold medal in reading between the lines

**Comment by albertodemichelis** [comment]
Actually I have regression tests since day one. Where are they? in my dev repo.
