### ISSUE TITLE
There is commits history that can be imported ?

### ISSUE THREAD

**Issue by mingodad** [albertodemichelis/squirrel#5]
Hello !
There is old commits history that can be imported ?
Cheers !

**Comment by albertodemichelis** [comment]
My personal repository dates back to 2002, before squirrel was called squirrel and way before distributed versioning system were trendy. So i t's full of binaries and other crap that should really not be added here. I will eventually create another two separated repos for 3.0.x and 2.x.

**Comment by albertodemichelis** [comment]
solved
