### ISSUE TITLE
getstackinfos(0) returns `getstackinfos`

### ISSUE THREAD

**Issue by zeromus** [albertodemichelis/squirrel#51]
This may just be a shortcoming in the documentation, but I discovered that `getstackinfos(0)` returns getstackinfos() itself. This is sensible, but a little surprising. The docs say:

`level = 0 is the current function, level = 1 is the caller`

Maybe it should say "level = 0 is `geststackinfos` itself; level = 1 is the current function; level = 2 is the caller."

I haven't tested it, but I would expect that thread.getstackinfos() may return different things depending on whether it's called on the current thread (if called on current thread, level 0 is getstackinfos; if called on another thread, level 0 is wherever the thread is currently running). Once more, that's pretty sensible, but it's worth drawing attention to this peculiarity.

If you can confirm that this is all according to design and agree that the docs could use some clarification, I'll draft those clarifications.

**Comment by aab29** [comment]
Yep, I think I agree with @zeromus 's proposed changes to the documentation.  💯 

This is a very minor quibble, but while we're talking about `getstackinfos`, I figured I'd point it out.  👈  To a native English speaker, it's a little strange to see *infos* written as a plural like that.  *Information* is almost always an uncountable noun, so I'd expect the function name to be `getstackinfo` (singular).  ℹ️  Of course, it might not be worth changing it at this point; I'll leave that up to you.  😺

**Comment by zeromus** [comment]
getstackinfos() would be accurate if it returned several stackinfo tables (the whole call stack). Since it returns one table for one stack level, getstackinfo() would make more sense. But I wouldn't bother changing it.

**Comment by albertodemichelis** [comment]
I agree if you want to rectify the documentation, and state that level 0 is getstackinfo() itself.
About the name, that is not a plural, it refers to a stackinfos structure not multiple information. So, as creator of the stackinfos structure and having consulted with my lawyers. I arrived to the conclusion that "stackinfos" is correct. :D

**Comment by zeromus** [comment]
p.s. you typed getstackinfo() on accident. maybe our fault for scrambling your brain with all this talk about it.

**Comment by albertodemichelis** [comment]
you got me!
