### ISSUE TITLE
Patch to allow accept typescript like declarations

### ISSUE THREAD

**Issue by mingodad** [albertodemichelis/squirrel#6]
Hello !
I have in squilu some modifications that allow scripts be written with a syntax like typescript for functions and function parameters types.
Also add some aliases to "local" such as "auto", "var", "let".

I can make a squirrel compatible patch if desired (or if someone want to do it) !
Cheers !

**Comment by albertodemichelis** [comment]
nop, sorry. I think it would make more sense to create a typescript implementation that generates squirrel compatible bytecode.
