### ISSUE TITLE
warning: this ‘if’ clause does not guard on sqapi.cpp

### ISSUE THREAD

**Issue by avelino** [albertodemichelis/squirrel#69]
Warning message at compile time the squirrel:

    sqapi.cpp: In function ‘SQRESULT sq_setdelegate(HSQUIRRELVM, SQInteger)’:
    sqapi.cpp:974:13: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
                 if(!_table(self)->SetDelegate(_table(mt))) return sq_throwerror(v, _SC("delagate cycle")); v->Pop();}
                 ^~
    sqapi.cpp:974:104: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
                 if(!_table(self)->SetDelegate(_table(mt))) return sq_throwerror(v, _SC("delagate cycle")); v->Pop();}

**Comment by iSLC** [comment]
I think that the `v->Pop();` statement comes in the outer scope, otherwise it has no purpose there since it's never reached because of the return.

Keeping with the current programming style in the library, the statement simply needs to be put on the next line:
```c++
if(!_table(self)->SetDelegate(_table(mt))) return sq_throwerror(v, _SC("delagate cycle"));
            v->Pop(); }
```
