### ISSUE TITLE
How hard to add "include" to the compiler ?

### ISSUE THREAD

**Issue by mingodad** [albertodemichelis/squirrel#7]
Hello !
How hard it'll be to add "include" capability in the compiler ?
I did a look at it, but it was clear to me where the better place to change the code.

Would be nice to have a standard way to use several scripts with something like "require" in lua.

I did a script to mimic "require" from lua (but it need to be loaded first):
```
local globals = getroottable();
globals.rawset("SQ_LIB", os.getenv("SQ_LIB"));
//SQ_LIB <- os.getenv("SQ_LIB");
//print("Preload", SQ_LIB);

function sq_require(fn, env=globals)
{
	if(!env) env = globals;
	env.dofile(format("%s/%s", SQ_LIB, fn));
}
```
I also did a change to sq.c to allow preload a script:
```
void PrintUsage()
{
	scfprintf(stderr,_SC("usage: sq <options> <scriptpath [args]>.\n")
		_SC("Available options are:\n")
		_SC("   -s              compiles the file to bytecode(default output 'out.cnut')\n")
		_SC("   -o              specifies output file for the -c option\n")
		_SC("   -c              compiles only\n")
		_SC("   -d              generates debug infos\n")
		_SC("   -v              displays version infos\n")
		_SC("   -p              preload given script file\n")
		_SC("   -h              prints help\n"));
}

void loadDefaultScript(HSQUIRRELVM v, const char *script)
{
    FILE *fb = fopen(script, "rb");
    if (!fb) return;
    fclose(fb);

    SQChar srcBoot[256];
    scsnprintf(srcBoot, sizeof(srcBoot), _SC("dofile(\"%s\", false);"), script);

    if(SQ_SUCCEEDED(sq_compilebuffer(v,srcBoot, strlen(srcBoot), _SC("defaultScript"), SQTrue, SQTrue))) {
        int callargs = 1;
        sq_pushroottable(v);
        callargs += push_program_args(v, 0, sq_main_argc, sq_main_argv);
        sq_call(v, callargs,SQFalse, SQTrue);
    }
}

int getargs(HSQUIRRELVM v,int argc, char* argv[],SQInteger *retval)
{
...
				case 'p':
					if(arg < argc) {
						arg++;
						preload = argv[arg];
                        loadDefaultScript(v, preload);
					}
					break;
				case 'v':

```

But it would be better to have it builtin in the compiler/language itself.

This repository implemented "import" and dynamic loading https://github.com/pfalcon/squirrel-lang .
Why not have it on squirrel ?
Cheers !

**Comment by albertodemichelis** [comment]
I think "require" doesn't belong to the core language. Squirrel as an embedded language should let the "user" decide how to load modules. However, I've been thinking since a while that there should be a something like that, maybe in "etc" or a separated "official" library. My original plan was to start a project called "fatsquirrel" that would be a bit more like nodejs/python, and have its own library policies.

**Comment by mingodad** [comment]
That's somehow how I use squirrel as squilu, I would like to see something like "fatsquirrel".
In my point of view squirrel has potential as it is but also as a pre typescript/javascript/java/c/c++ , I mean we can use it to develop a piece of code (because it's write/run) and after getting it working properly it's almost copy and paste as typescript/javascript/c/c++/java for a good subset of then.

That's why I've added "var", "auto", "let", "int?_t", "uint?_t", "char_t", "wchar_t"  as alias to "local" and accept typescript like type declaration.

Also I've did a dump the bytecode as squilu/squirrel script with the intention of be able to make code transformations/rewrite to other languages, and trying to make it easier to understand. Something like what "haxe language" is doing.

Also like you mention like nodejs/phyton having a http server out of the box make a huge difference, squilu is using "mongoose" http server (from the time it still was MIT license) but doesn't have an easy interface (I'm planing to change that).

Cheers !

**Comment by mingodad** [comment]
Or something with llvm like http://terralang.org/ would make it a serious scripting language to consider.

**Comment by albertodemichelis** [comment]
I did some screwing around with libuv bindings, but instead of using callbacks like in nodejs I used coroutines and suspend. I've been using this model for 10 years in my professional projects servers. It's a much better programming experience than nodejs as it gives readable callstacks, its debuggable, and people write async code without having to be experts. (Still some stuff like new connections is a callback, that spawns a new coroutine). A system like this but with a good set of libraries would be nice.
Interaction with other languages is not really in my agenda, I still want Squirrel's core to be small and primarily embedded.

**Comment by mingodad** [comment]
Can you share your libuv bindings ?

**Comment by albertodemichelis** [comment]
More than proper libuv bindings I made a prove of concept that uses coroutines instead of callbacks. I just bound some of the file interface and a simple http server. If you want I can mail you my test project, It is quite raugh and I only tested it on Windows/VC++.

**Comment by mingodad** [comment]
Hello !
Yes I want it, thank you !

**Comment by mingodad** [comment]
Hello !
I did a first implementation of "#include" for the compiler see https://github.com/mingodad/squilu/commit/483b2feb5b564b8ae70e262047c563381d12b30c I would appreciate any suggestion on how to improve it.
Right now it limits nested/recursive includes to 10 levels, it doesn't check for duplicate includes right now.
It would be nice if we could have squirrel/squilu dynamic scripting as macro processors.

Cheers !

**Comment by mingodad** [comment]
Hello !
I did a second simpler implementation of scripting compiler includes you can see it here https://github.com/mingodad/squilu/commit/10567abf3b3a89f2549557dc438dd199c52bf729 .
Cheers !

**Comment by albertodemichelis** [comment]
Sorry but I'm really not interested in adding #include. it doesn't belong in core squirrel. I think #include belongs in a pre-processor step at best. As a implementation note: calling fopen in the compiler would break many usage scenarios as many peaople(my company included) don't use fopen nor the raw file system to store scripts.
