### ISSUE TITLE
SquiLu start adding OS threads

### ISSUE THREAD

**Issue by mingodad** [albertodemichelis/squirrel#74]
Hello !
I just started adding support for OS threads on SquiLu and it could be backported to squirrel, right now if someone else needs it or want to contribute here is the relevant commit.
https://github.com/mingodad/squilu/commit/954642c3843cd2784c249f3ee76465f7cc24be29
Cheers !

**Comment by albertodemichelis** [comment]
The equivalent of pthread mutex on Windows is CRITICAL_SECTION. Windows mutex is much heavier, it is mostly used for cross process synchronization.

**Comment by zeromus** [comment]
critical section can be used for many of the same tasks as a pthread mutex, but it requires a lot of work to build something semantically correct.  A pthread mutex semantics at least are matched by windows semantics, although the performance could be a sour surprise (never happened to me though). There are other pthread services which are not easy at all to match.

see this enormous slab of code for reference: https://sourceforge.net/p/mingw-w64/code/6184/tree/trunk/mingw-w64-libraries/winpthreads/src/
