### ISSUE TITLE
GCC warns about sq.c because it includes a C++ header

### ISSUE THREAD

**Issue by paulsapps** [albertodemichelis/squirrel#85]
For example:

```
/home/travis/build/paulsapps/alive/3rdParty/squirrel/include/sqconfig.h:11:23: warning: ISO C90 does not support ‘long long’ [-Wlong-long]
 typedef unsigned long long SQHash; /*should be the same size of a pointer*/
                       ^
/home/travis/build/paulsapps/alive/3rdParty/squirrel/include/sqconfig.h:32:33: warning: C++ style comments are not allowed in ISO C90
 typedef __int64 SQRawObjectVal; //must be 64bits
```

Because sq.c is including sqconfig.h. What do you think of a PR to simply rename sq.c to sq.cpp so it builds and C++ and therefore "fixes" the warnings?

**Comment by zeromus** [comment]
This is useful as a test case that the squirrel headers can compile as C, which may be important to some people.

However judging from the warnings, that it compiles as C90 is not warranted. The penalty to using an unsupported compiler is warnings--lucky that it isn't errors! Let's say C99 is supported instead.

**Comment by paulsapps** [comment]
Hmm AFAIK this is the out of the box CMake config - GCC is not a supported compiler?

**Comment by jansol** [comment]
Another solution would be to use intptr_t from stdint.h but that is C99 as well, so not sure how much of a win it would be.

**Comment by zeromus** [comment]
so add set_source_files_properties(sq.c PROPERTIES COMPILE_FLAGS -std=c99) to sq/CMakeLists.txt  and add a comment that squirrel headers can only be fully guaranteed to compile as C with a C99 or better compiler

**Comment by paulsapps** [comment]
I'll create a PR for it eventually - I think travis and appveyor should probably be enabled on this repo too.

**Comment by jansol** [comment]
As for this issue, your GCC version would be very useful to know.

**Comment by paulsapps** [comment]
4.9.4
