### ISSUE TITLE
Why sqvm::IsEqual need a third parameter ?

### ISSUE THREAD

**Issue by mingodad** [albertodemichelis/squirrel#9]
Looking at the latest commits I noticed that sqvm::IsEqual is requiring a third bool parameter but it already return a bool.
Why this ?

I'm not sure on older squirrel versions but on squilu there isn't and it seems to work.
Cheers !

**Comment by albertodemichelis** [comment]
This was done for symmetry with other functions. the return value means "success" and the parameter called 'res' is the result of the comparison. However it seems that Equal never fails so the return value is a bit redundant here.

**Comment by albertodemichelis** [comment]
solved
