### ISSUE TITLE
DXSquirrel - Questions?

### ISSUE THREAD

**Issue by kphillisjr** [albertodemichelis/squirrel#96]
I figured this is the best place to ask about this Example/Project since there is some clear questions I cannot seem to find out about this mini project...

- Who is the Author? I assume that this is created by "Alberto Demichelis", however there is no information in the source archive about the author.
- What is the license of this example package? 
- Does this package run on the current Squirrel Code base (Squirrel 3.x)? The source code to my knowledge was last modified on July 4th of 2005.

**Comment by albertodemichelis** [comment]
The author is indeed me(Alberto Demichelis).
I never thought I had to license such a tiny piece of code. It's public domain.
It was originally for squirrel 2.x but I think the only difference is that sq_call gets an extra parameter so it should work with very minor changes.

**Comment by kphillisjr** [comment]
Thank you for the response, and honestly the copyright system (and patent system) is completely broken beyond believe when it comes to source code. A great example of this is that the whole Google VS Oracle lawsuit stemmed from 9 lines of code. Similarly, I know that implementing a single line of graphics shader source code could possible run afoul with patents.
